# Native mode
# Build first (requires GraalVM/Mandrel toolchain): mvn package -Dnative
# Resulting native executable is typically target/*-runner

FROM debian:bookworm-slim

WORKDIR /work/

COPY target/*-runner /work/application
RUN chmod 775 /work/application

EXPOSE 8080

CMD ["/work/application", "-Dquarkus.http.host=0.0.0.0"]
